# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\GUIs\qt_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 460, 401, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_entry = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.text_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.text_entry.setObjectName("text_entry")
        self.verticalLayout_2.addWidget(self.text_entry)
        self.enter_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.enter_button.setObjectName("enter_button")
        self.verticalLayout_2.addWidget(self.enter_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 401, 401))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 397, 397))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.output_text = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.output_text.setGeometry(QtCore.QRect(0, 0, 401, 401))
        self.output_text.setReadOnly(True)
        self.output_text.setObjectName("output_text")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.welcome_message = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.welcome_message.setReadOnly(True)
        self.welcome_message.setObjectName("welcome_message")
        self.horizontalLayout.addWidget(self.welcome_message)
        self.settings_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayout.addWidget(self.settings_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 422, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.text_entry.returnPressed.connect(self.enter_button.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_entry.setPlaceholderText(_translate("MainWindow", "Type Here..."))
        self.enter_button.setText(_translate("MainWindow", "Enter"))
        self.settings_button.setText(_translate("MainWindow", "..."))
